# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    blockcypher.token: '%env(BLOCKCYPHER_TOKEN)%'
    blockcypher.log.LogEnabled: true
    blockcypher.log.FileName: 'BlockCypher.log'
    blockcypher.log.LogLevel: 'DEBUG'
    
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
        
    App\Service\CryptoAnalyseService:
        arguments:
            $blockcypherToken: '%blockcypher.token%'
            $logEnabled: '%blockcypher.log.LogEnabled%'
            $logFileName: '%blockcypher.log.FileName%'
            $logLevel: '%blockcypher.log.LogLevel%'
            
    BlockCypher\Client\AddressClient: ~


    


    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    doctrine.orm.metadata.annotation_reader:
        class: Doctrine\Common\Annotations\AnnotationReader



